<?php

namespace App\Models;

use Bavix\Wallet\Interfaces\Wallet;
use Bavix\Wallet\Traits\HasWallet;
use Bavix\Wallet\Traits\HasWallets;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Membership extends Model implements Wallet
{
    use HasFactory, HasUlids, HasWallet, SoftDeletes;

    protected $fillable = [
        'name',
        'settlement_period',
        'team_id',
        'member_fee',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub#

        /*self::created(function ($model) {
            $model->createWallet([
                'name' => $model->name.' wallet'
            ]);
        });*/
    }

    protected $casts = [

    ];

    public function team(): BelongsToMany
    {
        return $this->belongsToMany(Team::class, 'membership_team');
    }

    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class);
    }

    public function boardMembers()
    {
        return $this->hasMany(BoardMember::class);
    }

    public function currenBoard()
    {

    }
}
